#ifndef FORMAT_H

#define FORMAT_H

// General Formatting
#define SHELL_ESCAPE_SEQ(X) "\033[" X "m"

#define RESET SHELL_ESCAPE_SEQ("0")
#define BRIGHT SHELL_ESCAPE_SEQ("1")
#define DIM SHELL_ESCAPE_SEQ("2")
#define UNDERSCORE SHELL_ESCAPE_SEQ("4")
#define BLINK SHELL_ESCAPE_SEQ("5")
#define REVERSE SHELL_ESCAPE_SEQ("7")
#define HIDDEN SHELL_ESCAPE_SEQ("8")

// Foreground Colors
#define FG_BLACK SHELL_ESCAPE_SEQ("30")
#define FG_RED SHELL_ESCAPE_SEQ("31")
#define FG_GREEN SHELL_ESCAPE_SEQ("32")
#define FG_YELLOW SHELL_ESCAPE_SEQ("33")
#define FG_BLUE SHELL_ESCAPE_SEQ("34")
#define FG_MAGENTA SHELL_ESCAPE_SEQ("35")
#define FG_CYAN SHELL_ESCAPE_SEQ("36")
#define FG_WHITE SHELL_ESCAPE_SEQ("37")

// Bold Foreground Colors
#define FG_BLACK_BOLD SHELL_ESCAPE_SEQ("1;30")
#define FG_RED_BOLD SHELL_ESCAPE_SEQ("1;31")
#define FG_GREEN_BOLD SHELL_ESCAPE_SEQ("1;32")
#define FG_YELLOW_BOLD SHELL_ESCAPE_SEQ("1;33")
#define FG_BLUE_BOLD SHELL_ESCAPE_SEQ("1;34")
#define FG_MAGENTA_BOLD SHELL_ESCAPE_SEQ("1;35")
#define FG_CYAN_BOLD SHELL_ESCAPE_SEQ("1;36")
#define FG_WHITE_BOLD SHELL_ESCAPE_SEQ("1;37")

// Background Colors
#define BG_BLACK SHELL_ESCAPE_SEQ("40")
#define BG_RED SHELL_ESCAPE_SEQ("41")
#define BG_GREEN SHELL_ESCAPE_SEQ("42")
#define BG_YELLOW SHELL_ESCAPE_SEQ("43")
#define BG_BLUE SHELL_ESCAPE_SEQ("44")
#define BG_MAGENTA SHELL_ESCAPE_SEQ("45")
#define BG_CYAN SHELL_ESCAPE_SEQ("46")
#define BG_WHITE SHELL_ESCAPE_SEQ("47")

#endif /* end of include guard FORMAT_H */
